### ISSUE TITLE
Power Automate changed how the connector is called - "expected string got object" error

### ISSUE THREAD

**Issue by HanaSrek** [garrytrinder/harvest-api-powerplatform-custom-connector#2]
Hello Garry @garrytrinder , 
thanks for the connector, when I tried it in the past it worked great.

Recently I´ve tried to use it in a cloudflow but I get an error.
I have set the connector with your manual. During Test within connector details everything works fine and I get data as expected.

Problem is that if used in cloud flow following error is shown: "Rozhraní API in-5fharvest-20api-20v2-5f89ef4f865c4ed1d3 vrátilo neplatnou odpověď pro operaci pracovního postupu List_time_entries typu OpenApiConnection. Podrobnosti o chybě: Operace rozhraní API GetTimeEntries vyžaduje, aby vlastnost body byla typu String, ale přitom je typu Object."

In english: "...property body should be String but it is Object."

Thanks a lot for your answer
Any help would be highly appreciated
Take care
Hana

**Comment by garrytrinder** [comment]
Hey @HanaSrek 👋🏻

Thank you for reporting this.

I'm happy to take a look at the issue however just to se some expectations with you, I am busy for the next few days so won't be able to take a look into this until early next week.

**Comment by garrytrinder** [comment]
@HanaSrek I've just pushed an update as a PR. Would you be able to test the change to see if it resolves your issue?

You can view the new json file below

https://github.com/garrytrinder/harvest-api-powerplatform-custom-connector/blob/c23aa46990c354d36979ff4808cc801511a5efcd/Harvest-API.swagger.json

**Comment by HanaSrek** [comment]
@garrytrinder 
It seems to be working now. 
Thanks a lot
Great job

**Comment by garrytrinder** [comment]
No problem, thanks for raising the issue and testing 👍🏻

I'll merge the fix into the main branch.
